name: e_commerce_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  phone_numbers_parser: ^8.2.1
  email_validator: ^2.1.17
  anim_search_bar: ^2.0.3
  google_fonts: ^6.2.1
  salomon_bottom_bar: ^3.3.2
  sqflite: ^2.3.3+1
  carousel_slider: ^4.2.1
  u_credit_card: ^1.3.0
  cached_network_image: ^3.3.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
       - asset: fonts/MontserratAlternates-Regular.ttf
